/*
* generated by Xtext
*/
package org.xtext.example.myFetl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FETLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.myFetl.ui.internal.FETLActivator.getInstance().getInjector("org.xtext.example.myFetl.FETL");
	}
	
}
