/**
 * generated by Xtext
 */
package org.xtext.example.fileEctl.serializer;

import org.xtext.example.fileEctl.serializer.AbstractFilEctlSyntacticSequencer;

@SuppressWarnings("all")
public class FilEctlSyntacticSequencer extends AbstractFilEctlSyntacticSequencer {
}
