/**
 * generated by Xtext
 */
package org.xtext.example.fileEctl.serializer;

import org.xtext.example.fileEctl.serializer.AbstractFilEctlSemanticSequencer;

@SuppressWarnings("all")
public class FilEctlSemanticSequencer extends AbstractFilEctlSemanticSequencer {
}
