/*
 * generated by Xtext
 */
package org.xtext.example.miniFetl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.miniFetl.ui.internal.FetlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FetlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FetlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FetlActivator.getInstance().getInjector(FetlActivator.ORG_XTEXT_EXAMPLE_MINIFETL_FETL);
	}
	
}
