/*
* generated by Xtext
*/
package org.xtext.example.miniFetl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.miniFetl.services.FetlGrammarAccess;

public class FetlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FetlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.miniFetl.parser.antlr.internal.InternalFetlParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.miniFetl.parser.antlr.internal.InternalFetlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public FetlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FetlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
