/*
 * generated by Xtext
 */
package org.xtext.example.miniFetl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FetlRuntimeModule extends org.xtext.example.miniFetl.AbstractFetlRuntimeModule {

}
