/*
* generated by Xtext
*/
package org.xtext.example.miniFetl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FetlStandaloneSetup extends FetlStandaloneSetupGenerated{

	public static void doSetup() {
		new FetlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

