/**
 * generated by Xtext
 */
package org.xtext.example.miniFetl.serializer;

import org.xtext.example.miniFetl.serializer.AbstractFetlSemanticSequencer;

@SuppressWarnings("all")
public class FetlSemanticSequencer extends AbstractFetlSemanticSequencer {
}
