/**
 * generated by Xtext
 */
package org.xtext.example.miniFetl.validation;

import org.xtext.example.miniFetl.validation.AbstractFetlValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class FetlValidator extends AbstractFetlValidator {
}
