/*
 * generated by Xtext
 */
package org.xtext.example.fileEctl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FilEctlUiModule extends org.xtext.example.fileEctl.ui.AbstractFilEctlUiModule {
	public FilEctlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
