/*
 * generated by Xtext
 */
package org.xtext.example.fileEctl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FilEctlRuntimeModule extends org.xtext.example.fileEctl.AbstractFilEctlRuntimeModule {

}
