/**
 * generated by Xtext
 */
package org.xtext.example.myFetl.validation;

import org.xtext.example.myFetl.validation.AbstractFETLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class FETLValidator extends AbstractFETLValidator {
}
