/**
 * generated by Xtext
 */
package org.xtext.example.myFetl.ui.contentassist;

import org.xtext.example.myFetl.ui.contentassist.AbstractFETLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class FETLProposalProvider extends AbstractFETLProposalProvider {
}
