/*
 * generated by Xtext
 */
package org.xtext.example.miniFetl.ui.contentassist

import org.xtext.example.miniFetl.ui.contentassist.AbstractFetlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FetlProposalProvider extends AbstractFetlProposalProvider {
}
