/*
 * generated by Xtext
 */
package org.xtext.example.myFetl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FETLUiModule extends org.xtext.example.myFetl.ui.AbstractFETLUiModule {
	public FETLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
