/*
 * generated by Xtext
 */
package org.xtext.example.myFetl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.myFetl.ui.internal.FETLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FETLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FETLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FETLActivator.getInstance().getInjector(FETLActivator.ORG_XTEXT_EXAMPLE_MYFETL_FETL);
	}
	
}
