/*
 * generated by Xtext
 */
package org.xtext.example.fileEctl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.fileEctl.ui.internal.FilEctlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FilEctlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FilEctlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FilEctlActivator.getInstance().getInjector(FilEctlActivator.ORG_XTEXT_EXAMPLE_FILEECTL_FILECTL);
	}
	
}
