/**
 * generated by Xtext
 */
package org.xtext.example.myFetl.serializer;

import org.xtext.example.myFetl.serializer.AbstractFETLSyntacticSequencer;

@SuppressWarnings("all")
public class FETLSyntacticSequencer extends AbstractFETLSyntacticSequencer {
}
