/*
 * generated by Xtext
 */
package org.xtext.example.myFetl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FETLRuntimeModule extends org.xtext.example.myFetl.AbstractFETLRuntimeModule {

}
