/*
* generated by Xtext
*/
package org.xtext.example.myFetl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FETLStandaloneSetup extends FETLStandaloneSetupGenerated{

	public static void doSetup() {
		new FETLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

