/**
 * generated by Xtext
 */
package org.xtext.example.fileEctl.ui.contentassist;

import org.xtext.example.fileEctl.ui.contentassist.AbstractFilEctlProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class FilEctlProposalProvider extends AbstractFilEctlProposalProvider {
}
