/*
* generated by Xtext
*/
package org.xtext.example.miniFetl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FetlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.miniFetl.ui.internal.FetlActivator.getInstance().getInjector("org.xtext.example.miniFetl.Fetl");
	}
	
}
