/*
 * generated by Xtext
 */
package org.xtext.example.miniFetl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FetlUiModule extends org.xtext.example.miniFetl.ui.AbstractFetlUiModule {
	public FetlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
